apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-secret
type: Opaque
data:
  # credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: template.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentialsSecretRef:
    namespace: crossplane-system
    name: example-provider-secret
    key: credentials