apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: crossplane-system
type: Opaque
data:
  credentials.json: ewogIGNyZWRlbnRpYWxzOiBCQVNFNjRFTkNPREVEX1BST1ZJREVSX0NSRURTLAogIFR5cGU6ICJDcmVkaXRDYXJkIiwKICBDYXJkVHlwZTogIlZpc2EiLAogIE51bWJlcjogIjExMTEyMjIyMzMzMzQ0NDQiLAogIEV4cGlyYXRpb246ICIwMTIzIiwKICBTZWN1cml0eUNvZGU6ICIxMjMiLAp9
---
apiVersion: provider-pizza.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: payment-secret
      key: payment-secret-key

# # credentials.json is base64 encoded and contains the following data
# {
#   Type: "CreditCard",
#   CardType: "Visa",
#   Number: "1111222233334444",
#   Expiration: "0123",
#   SecurityCode: "123",
# }

